name: Build TrollStore IPA

on: 
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-15 # 👈 终极物理外挂：直接向 GitHub 申请最新的 macOS 15 服务器，自带 Xcode 16，秒杀一切新特性！

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' 

      # (那个坑爹的 Force Downgrade 降级脚本已经被我彻底删了，绝不再乱改依赖！)

      - name: Install Dependencies
        run: |
          cd simple_live_app
          flutter pub get

      - name: Build Unsigned iOS App
        run: |
          cd simple_live_app
          flutter build ios --release --no-codesign

      - name: Package into TrollStore IPA
        run: |
          cd simple_live_app/build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -qq -r simple_live_trollstore.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4 
        with:
          name: SimpleLive-TrollStore-IPA
          path: simple_live_app/build/ios/iphoneos/simple_live_trollstore.ipa
