name: Build TrollStore IPA

on: 
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 
        with:
          # 👇 终极时光机启动：精确降落到 12月22日 的完美稳定版！
          ref: 'fcadd05' 

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' 

      - name: Install Dependencies
        run: |
          cd simple_live_app
          flutter pub get

      - name: Build Unsigned iOS App
        run: |
          cd simple_live_app
          flutter build ios --release --no-codesign

      - name: Package into TrollStore IPA
        run: |
          cd simple_live_app/build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -qq -r simple_live_trollstore.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4 
        with:
          name: SimpleLive-TrollStore-IPA
          path: simple_live_app/build/ios/iphoneos/simple_live_trollstore.ipa
